### ISSUE TITLE
Issues With Saving

### ISSUE THREAD

**Issue by Elemperor1** [44670/desmume-wasm#133]
Hi there,
I am attempting to play on a 13 pro max. Unfortunately, whenever I try saving a game, either to Dropbox or manually, it sends me back to the main menu. This wouldn’t be a problem except whenever I try clicking on the upload file button, it isn’t there, instead just replaced with a bit of text that says loading. So, I try and exit the app and then swipe up, however, when I get back to the game, it hasn’t saved my data, whether locally or to Dropbox. I was wondering if you would be able to help me with this?

**Comment by 44670** [comment]
First of all, you have to save in the game, which is written in the [README.md](https://github.com/44670/desmume-wasm/blob/master/README.md).

Downloading save data from dropbox will result a reload of the web page, it's an expected behavior, if it stuck on "Loading...", just close & reopen the page.

**Comment by Elemperor1** [comment]
So, I get that, but the problem is with new super Mario bros, you can’t save manually.

**Comment by 44670** [comment]
By googling that game, you need to beat a tower or castle before saving your progress.

**Comment by Elemperor1** [comment]
I got it to work, thank you so much! Great program btw. I was wondering, is it possible to take this and make a version for the 3ds?

**Comment by 44670** [comment]
Not possible for a playable speed I think.
