### ISSUE TITLE
Using .4gs save data in PC emulator

### ISSUE THREAD

**Issue by TenteiTudo** [44670/desmume-wasm#140]
Olá! É um excelente emulador! Mas não consigo exportar o arquivo .sav… Na pasta do Dropbox só existe um arquivo de extensão .4gz. Que não é reconhecido quando eu quero abrir no emulador para PC. Podem me ajudar em como converter ele?

==Translated==
Hi, it's an excellent emulator! But I can't export the .sav file... In the Dropbox folder there is only a file with extension .4gz. Which is not recognized when I want to open it in the PC emulator. Can you help me how to convert it?

**Comment by 44670** [comment]
You can export 4gs files from the emulator, this is actually in vba-next format and should work in the vba-next core of retroarch.

The vba-next format is not compatible with any other emulator, so perhaps this tool could be used to convert it.

https://github.com/libretro/vba-next/tree/master/libretro/gbaconv

However, compatibility is not guaranteed due to differences in BIOS implementation. The easiest way is to use 44vba directly on desktop Chrome.



Please try to ask your questions in English so that what you ask will be helpful to others.

**Comment by 44670** [comment]
By the way, you seem to have asked the question in the wrong repo, you probably meant to ask it at https://github.com/44670/44vba
