### ISSUE TITLE
Enhance GUI?

### ISSUE THREAD

**Issue by Xolverr** [44670/desmume-wasm#152]
Hey 44670, I was messing around with https://ds.44670.org today and I was wondering if you would be interested in implementing something similar to what I've done in the two attached files.

I thought the site might look better if it was styled like a **native iOS application**, so I put together a demo for the settings page. I would continue to do the entire site, but I've tried cloning the website to work on it, but once I go to the clone, the site redirects to yours.

If there is any way to prevent this from happening so I can continue development, please let me know!

>To see my implementation, go to ds.44670.org, click **⚙ Settings...**, click **Back**, and click **⚙ Settings...** again.
>
>Copy the contents of [**index.html**](https://github.com/44670/desmume-wasm/files/11400337/index.html.txt)
>
>Open DevTools, right-click on `<html>` and click **Edit as HTML**.
>
>Press **Ctrl+A**, then **Ctrl+V**.
>
>Now, copy the contents of [**dark.css**](https://github.com/44670/desmume-wasm/files/11400343/dark.css.txt)
>
>Click **Sources**, then `dark.css?ver=v62`
>
>Again press **Ctrl+A**, then **Ctrl+V**.
>
>(in order to see what it would look like on an iPhone, press **Ctrl+Shift+M**, then select your device under the **Devices** dropdown.)

Thank you!

**Comment by 44670** [comment]
Sorry, due to the sensitivity of this application to performance (simulating a DS in a browser is a very challenging task), we will keep the UI as minimal as possible to avoid impacting performance during gameplay.

Additionally, we do not want this application to confused with native iOS apps in look and feel. We want users to be very clear that this is a web page, so they understand that using it will not pose any security issues and that they are aware of the performance differences compared to a native emulator.
