### ISSUE TITLE
Importing save data crashes game

### ISSUE THREAD

**Issue by thonkinator** [44670/desmume-wasm#17]
So I’m trying to play the eCDP dump on this emulator, however as it requires a specific save file to play I need to load a specific .sav file. But, when I go to menu > import save data and select the file, i’m sent back to the home page where I’m either prompted to choose a new game ROM, or it just says Loading… forever. Am I doing something wrong?

**Comment by arxadia** [comment]
I have a similar problem when importing saves for literally any rom, have you found a way to work around this? Sometimes it just gives me a blank white screen too and it won’t load anything

**Comment by HeikoHeftig** [comment]
I have the same problem. But it says File Save loaded but brings me back to the rom selection and nothing happens… pls help

**Comment by Candiekrustie** [comment]
So I wanted to play Pokémon white 2 since it’s been years since I’ve played it, but it got slower and once I saved, after I defeated the first gym and decided to take a break, it restarted all my data. I decided to play again and I got to virbank complex to catch a growlithe, it got slower again and then I realized if you save while it gets slower, it’ll be that way until it resets all your data. Can you please fix it? Other than that, good emulator!

**Comment by 44670** [comment]
Duplicate of #13 

Only .dsv format is supported.
