### ISSUE TITLE
Imported save does not work

### ISSUE THREAD

**Issue by gxvibb** [44670/desmume-wasm#86]
I am playing the Tomodachi Collection English Translation on my iPhone 13 Pro Max, and I had imported my save file, closed and reopened the app like it said to, and my save file was completely empty when I reopened the app (it would act like i didn’t have a save file). I have tried reimporting my save file several times, and even tried using other saves and nothing has worked.

**Comment by 44670** [comment]
Which save file you imported from? Is it exported from ds.44670.org?

**Comment by gxvibb** [comment]
> Which save file you imported from? Is it exported from ds.44670.org? Have you saved in the game and saw the 'auto-saving' banner before exporting?

Yes, it is from ds.44670.org and yes, it has successfully auto-saved. It saves just fine when it loads the auto save, but when I manually import my save it does not.

**Comment by 44670** [comment]
Interesting, what's the file name of the exported save, is it a .4dsav file?

**Comment by Morello93** [comment]
Hi, I have a similar problem but between DS Player and Desktop Desmume.
Until few days ago, I was able to export my save in .dsv format and import it in Desmume on Windows.

Now, since the exported save file is .4dsav or .4dsaz, Desmume will not read it anymore.

Anything I can do to fix it? Even a decompress program would work for me, to convert the .4dsav/.4dsaz to .dsv.

**Comment by 44670** [comment]
It may not compatible due to differences in bios implementations in different emulators/different version of the same emulator, we have received tons of reporting.

You can also use DS Player on PC with Chrome.
